# Generated by Django 5.1.4 on 2025-01-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_subscription_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='terms_and_privacy_policy_acceptance',
            field=models.BooleanField(default=False),
        ),
    ]
