# Generated by Django 5.1.4 on 2025-01-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_name_alter_post_slug_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/post_images/logo.png', upload_to='post_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.TextField(default='A post by Om.'),
        ),
    ]
